### ISSUE TITLE
ValueError: cannot reshape array of size 0 into shape (0,newaxis)

### ISSUE THREAD

**Issue by gaggiag** [asuni/wavelet_prosody_toolkit#33]
Hi! I've installed the package successfully (MacOS), opened the GUI successfully, but when I try to upload a file - python crashes and I get the following error:
ValueError: cannot reshape array of size 0 into shape (0,newaxis)

Any idea what might cause that?
Thanks!

**Comment by gDegano** [comment]
There might be some incompatibility with the new python version. If you are using 3.8 it is likely that you will encounter issues.
SOLVE: use an environment with python <=3.7 and the defaults/GUI will run.

**Comment by JIE-CHI** [comment]
I got the same error, and I solved it by removing the `dtype='int16',` in the following codes when reading the wav files. 

https://github.com/asuni/wavelet_prosody_toolkit/blob/fc7ad42149c1b34279857f8dec660da32ead6112/wavelet_prosody_toolkit/prosody_tools/misc.py#L47

**Comment by seblemaguer** [comment]
@JIE-CHI are you on mac os as well? I am trying to reproduce this issue, and it doesn't happen on my side.

**Comment by JIE-CHI** [comment]
No, I am on a Linux machine. This issue only occurs to me with certain audio files where all values are near 0. Because they are all converted to`int` (0), you will divide 0 in normalization, e.g.
 https://github.com/asuni/wavelet_prosody_toolkit/blob/14d28cfc9333fe471d0ee41b713ad608097fbdd7/wavelet_prosody_toolkit/prosody_tools/pitch_tracker.py#L155

**Comment by seblemaguer** [comment]
ok, thanks a lot for the trace :)
